# .streamlit/secrets.toml

# Clave de la API de Google Gemini
#GEMINI_API_KEY = "AIzaSyBGJKE2DzpLJNnRkuHGS7URHyOcqNQBlz0"
GEMINI_API_KEY = "AIzaSyBel1VcwRMlYTOiO4fl7LhqnDndVC6vrvA"
# Opcional: si tuvieras otros secretos, irían aquí.
# Por ejemplo, credenciales de una base de datos externa:
# db_username = "usuario_seguro"
# db_password = "password_secreto"